# node-catch-all
Node module that catches any and all (otherwise unhanded) exceptions, even those called asynchronously, thrown from the context of the calling funtion
